server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/erandakaanupama/pick-my-ride-config-store
          search-paths:
            - '*service'
